; Using seed 890315
	.byte 	1	; *** Load Integer 99999 ***
	.dword 	$1869f
	.byte 	0,$01
	.byte 	1     ; *** Load Float -0.810638 ***
	.dword 	$cf85f8d2
	.byte 	$80,$80
	.byte 	1     ; *** Load Float -102.48 ***
	.dword 	$ccf5c28f
	.byte 	$87,$80
	.byte 	$2b   ; *** Command + ***
	.byte 	1     ; *** Load Float -103.290638 ***
	.dword 	$ce94ce81
	.byte 	$87,$80
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 2.768391 ***
	.dword 	$b12d5171
	.byte 	$82,$0
	.byte 	1     ; *** Load Float 4.0 ***
	.dword 	$80000000
	.byte 	$83,$0
	.byte 	$2d   ; *** Command - ***
	.byte 	1     ; *** Load Float -1.2316090000000002 ***
	.dword 	$9da55d1c
	.byte 	$81,$80
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 3.910975 ***
	.dword 	$fa4d6a16
	.byte 	$82,$0
	.byte 	1     ; *** Load Float -9.0 ***
	.dword 	$90000000
	.byte 	$84,$80
	.byte 	$2f   ; *** Command / ***
	.byte 	1     ; *** Load Float -0.4345527777777778 ***
	.dword 	$de7db3a1
	.byte 	$7f,$80
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float -2.0 ***
	.dword 	$80000000
	.byte 	$82,$80
	.byte 	1     ; *** Load Float 19.0 ***
	.dword 	$98000000
	.byte 	$85,$0
	.byte 	$7e   ; *** Command ~ ***
	.byte 	1     ; *** Load Float -1 ***
	.dword 	$80000000
	.byte 	$81,$80
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 6.148325 ***
	.dword 	$c4bf1412
	.byte 	$83,$0
	.byte 	1     ; *** Load Float 1.181577317765914e-12 ***
	.dword 	$a64acf31
	.byte 	$59,$0
	.byte 	$7e   ; *** Command ~ ***
	.byte 	1     ; *** Load Float 1 ***
	.dword 	$80000000
	.byte 	$81,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float -18.0 ***
	.dword 	$90000000
	.byte 	$85,$80
	.byte 	1     ; *** Load Float 1.051512 ***
	.dword 	$8697f1f9
	.byte 	$81,$0
	.byte 	$2a   ; *** Command * ***
	.byte 	1     ; *** Load Float -18.927216 ***
	.dword 	$976af038
	.byte 	$85,$80
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 5.655817 ***
	.dword 	$b4fc73ee
	.byte 	$83,$0
	.byte 	1     ; *** Load Float -5646095.220736 ***
	.dword 	$ac4e1e71
	.byte 	$97,$80
	.byte 	$2a   ; *** Command * ***
	.byte 	1     ; *** Load Float -31933281.33305742 ***
	.dword 	$f3a1b0aa
	.byte 	$99,$80
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 5.0 ***
	.dword 	$a0000000
	.byte 	$83,$0
	.byte 	1     ; *** Load Float -2.207274519605562e-12 ***
	.dword 	$9b52b90a
	.byte 	$5a,$80
	.byte 	$2a   ; *** Command * ***
	.byte 	1     ; *** Load Float -1.103637259802781e-11 ***
	.dword 	$c227674d
	.byte 	$5c,$80
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float -6.0 ***
	.dword 	$c0000000
	.byte 	$83,$80
	.byte 	1     ; *** Load Float 3.724867 ***
	.dword 	$ee64388e
	.byte 	$82,$0
	.byte 	$7e   ; *** Command ~ ***
	.byte 	1     ; *** Load Float -1 ***
	.dword 	$80000000
	.byte 	$81,$80
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 4.606481 ***
	.dword 	$93684ad7
	.byte 	$83,$0
	.byte 	1     ; *** Load Float 45.17 ***
	.dword 	$b4ae147a
	.byte 	$86,$0
	.byte 	$2b   ; *** Command + ***
	.byte 	1     ; *** Load Float 49.776481000000004 ***
	.dword 	$c71b1dd5
	.byte 	$86,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 7.633596 ***
	.dword 	$f4466b1e
	.byte 	$83,$0
	.byte 	1     ; *** Load Float -4.0 ***
	.dword 	$80000000
	.byte 	$83,$80
	.byte 	$2f   ; *** Command / ***
	.byte 	1     ; *** Load Float -1.908399 ***
	.dword 	$f4466b1e
	.byte 	$81,$80
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 3.226939 ***
	.dword 	$ce862b27
	.byte 	$82,$0
	.byte 	1     ; *** Load Float 416.99 ***
	.dword 	$d07eb851
	.byte 	$89,$0
	.byte 	$2b   ; *** Command + ***
	.byte 	1     ; *** Load Float 420.216939 ***
	.dword 	$d21bc4a8
	.byte 	$89,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 17.0 ***
	.dword 	$88000000
	.byte 	$85,$0
	.byte 	1     ; *** Load Float 18.0 ***
	.dword 	$90000000
	.byte 	$85,$0
	.byte 	$2a   ; *** Command * ***
	.byte 	1     ; *** Load Float 306.0 ***
	.dword 	$99000000
	.byte 	$89,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float -14840.823808000001 ***
	.dword 	$e7e34b94
	.byte 	$8e,$80
	.byte 	1     ; *** Load Float -1931281.956864 ***
	.dword 	$ebc08fa7
	.byte 	$95,$80
	.byte 	$7e   ; *** Command ~ ***
	.byte 	1     ; *** Load Float 1 ***
	.dword 	$80000000
	.byte 	$81,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 893190469847.0891 ***
	.dword 	$cff64cf8
	.byte 	$a8,$0
	.byte 	1     ; *** Load Float 9.19558 ***
	.dword 	$9321187e
	.byte 	$84,$0
	.byte 	$2a   ; *** Command * ***
	.byte 	1     ; *** Load Float 8213404420716.495 ***
	.dword 	$ef0aa1b1
	.byte 	$ab,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 8.708695 ***
	.dword 	$8b56d091
	.byte 	$84,$0
	.byte 	1     ; *** Load Float -8.0 ***
	.dword 	$80000000
	.byte 	$84,$80
	.byte 	$2f   ; *** Command / ***
	.byte 	1     ; *** Load Float -1.088586875 ***
	.dword 	$8b56d091
	.byte 	$81,$80
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 8682729.373696 ***
	.dword 	$847ce95f
	.byte 	$98,$0
	.byte 	1     ; *** Load Float -19.0 ***
	.dword 	$98000000
	.byte 	$85,$80
	.byte 	$7e   ; *** Command ~ ***
	.byte 	1     ; *** Load Float 1 ***
	.dword 	$80000000
	.byte 	$81,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 17.0 ***
	.dword 	$88000000
	.byte 	$85,$0
	.byte 	1     ; *** Load Float 8.434507 ***
	.dword 	$86f3bd9c
	.byte 	$84,$0
	.byte 	$2b   ; *** Command + ***
	.byte 	1     ; *** Load Float 25.434507 ***
	.dword 	$cb79dece
	.byte 	$85,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 169.9 ***
	.dword 	$a9e66666
	.byte 	$88,$0
	.byte 	1     ; *** Load Float -8.0 ***
	.dword 	$80000000
	.byte 	$84,$80
	.byte 	$2d   ; *** Command - ***
	.byte 	1     ; *** Load Float 177.9 ***
	.dword 	$b1e66666
	.byte 	$88,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 13.0 ***
	.dword 	$d0000000
	.byte 	$84,$0
	.byte 	1     ; *** Load Float 1.209657 ***
	.dword 	$9ad60a63
	.byte 	$81,$0
	.byte 	$2a   ; *** Command * ***
	.byte 	1     ; *** Load Float 15.725541 ***
	.dword 	$fb9bd0e1
	.byte 	$84,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 18.0 ***
	.dword 	$90000000
	.byte 	$85,$0
	.byte 	1     ; *** Load Float 17.0 ***
	.dword 	$88000000
	.byte 	$85,$0
	.byte 	$2f   ; *** Command / ***
	.byte 	1     ; *** Load Float 1.0588235294117647 ***
	.dword 	$87878787
	.byte 	$81,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 7451278632.288256 ***
	.dword 	$de10be94
	.byte 	$a1,$0
	.byte 	1     ; *** Load Float 6.869421 ***
	.dword 	$dbd24bfd
	.byte 	$83,$0
	.byte 	$7e   ; *** Command ~ ***
	.byte 	1     ; *** Load Float 1 ***
	.dword 	$80000000
	.byte 	$81,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 4.0 ***
	.dword 	$80000000
	.byte 	$83,$0
	.byte 	1     ; *** Load Float 129.28512 ***
	.dword 	$8148fd9f
	.byte 	$88,$0
	.byte 	$7e   ; *** Command ~ ***
	.byte 	1     ; *** Load Float -1 ***
	.dword 	$80000000
	.byte 	$81,$80
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 7.725168 ***
	.dword 	$f7349385
	.byte 	$83,$0
	.byte 	1     ; *** Load Float 6.704608 ***
	.dword 	$d68c2613
	.byte 	$83,$0
	.byte 	$2f   ; *** Command / ***
	.byte 	1     ; *** Load Float 1.1522176986335368 ***
	.dword 	$937bde9a
	.byte 	$81,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 5.10096549987793e-07 ***
	.dword 	$88ed9168
	.byte 	$6c,$0
	.byte 	1     ; *** Load Float 9.541238 ***
	.dword 	$98a8e92d
	.byte 	$84,$0
	.byte 	$2f   ; *** Command / ***
	.byte 	1     ; *** Load Float 5.3462302270186844e-08 ***
	.dword 	$e59e6c49
	.byte 	$68,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 0.0 ***
	.dword 	$0
	.byte 	$80,$40
	.byte 	1     ; *** Load Float 2.91498 ***
	.dword 	$ba8f0846
	.byte 	$82,$0
	.byte 	$2a   ; *** Command * ***
	.byte 	1     ; *** Load Float 0.0 ***
	.dword 	$0
	.byte 	$80,$40
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 9.560549 ***
	.dword 	$98f8023a
	.byte 	$84,$0
	.byte 	1     ; *** Load Float 46236346311887.555 ***
	.dword 	$a834f3fd
	.byte 	$ae,$0
	.byte 	$2a   ; *** Command * ***
	.byte 	1     ; *** Load Float 442044854495770.25 ***
	.dword 	$c904cb43
	.byte 	$b1,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 5.903417 ***
	.dword 	$bce8cac4
	.byte 	$83,$0
	.byte 	1     ; *** Load Float 4.087682 ***
	.dword 	$82ce4a7b
	.byte 	$83,$0
	.byte 	$2b   ; *** Command + ***
	.byte 	1     ; *** Load Float 9.991099 ***
	.dword 	$9fdb8aa0
	.byte 	$84,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 0.730039 ***
	.dword 	$bae3d5fd
	.byte 	$80,$0
	.byte 	1     ; *** Load Float -12.21 ***
	.dword 	$c35c28f5
	.byte 	$84,$80
	.byte 	$2f   ; *** Command / ***
	.byte 	1     ; *** Load Float -0.059790253890253886 ***
	.dword 	$f4e6a011
	.byte 	$7c,$80
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 3.435549 ***
	.dword 	$dbe008e9
	.byte 	$82,$0
	.byte 	1     ; *** Load Float 345.73 ***
	.dword 	$acdd70a3
	.byte 	$89,$0
	.byte 	$2d   ; *** Command - ***
	.byte 	1     ; *** Load Float -342.29445100000004 ***
	.dword 	$ab25b092
	.byte 	$89,$80
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 4930648225.611776 ***
	.dword 	$92f1dc50
	.byte 	$a1,$0
	.byte 	1     ; *** Load Float 0.0 ***
	.dword 	$0
	.byte 	$80,$40
	.byte 	$2a   ; *** Command * ***
	.byte 	1     ; *** Load Float 0.0 ***
	.dword 	$0
	.byte 	$80,$40
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float -15.0 ***
	.dword 	$f0000000
	.byte 	$84,$80
	.byte 	1     ; *** Load Float 561.34 ***
	.dword 	$8c55c28f
	.byte 	$8a,$0
	.byte 	$2a   ; *** Command * ***
	.byte 	1     ; *** Load Float -8420.1 ***
	.dword 	$83906666
	.byte 	$8e,$80
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 0.0 ***
	.dword 	$0
	.byte 	$80,$40
	.byte 	1     ; *** Load Float -19.0 ***
	.dword 	$98000000
	.byte 	$85,$80
	.byte 	$2f   ; *** Command / ***
	.byte 	1     ; *** Load Float -0.0 ***
	.dword 	$0
	.byte 	$80,$40
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 17.0 ***
	.dword 	$88000000
	.byte 	$85,$0
	.byte 	1     ; *** Load Float 9.295606 ***
	.dword 	$94bacd5b
	.byte 	$84,$0
	.byte 	$2a   ; *** Command * ***
	.byte 	1     ; *** Load Float 158.02530199999998 ***
	.dword 	$9e067a31
	.byte 	$88,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 1.5018249511718752e-05 ***
	.dword 	$fbf6e3f7
	.byte 	$70,$0
	.byte 	1     ; *** Load Float 9.868548 ***
	.dword 	$9de59296
	.byte 	$84,$0
	.byte 	$2a   ; *** Command * ***
	.byte 	1     ; *** Load Float 0.00014820831618237308 ***
	.dword 	$9b685def
	.byte 	$74,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 9.0 ***
	.dword 	$90000000
	.byte 	$84,$0
	.byte 	1     ; *** Load Float 9.0 ***
	.dword 	$90000000
	.byte 	$84,$0
	.byte 	$2a   ; *** Command * ***
	.byte 	1     ; *** Load Float 81.0 ***
	.dword 	$a2000000
	.byte 	$87,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 8.630839 ***
	.dword 	$8a17eaa2
	.byte 	$84,$0
	.byte 	1     ; *** Load Float 234479.41939199998 ***
	.dword 	$e4fbdad7
	.byte 	$92,$0
	.byte 	$2a   ; *** Command * ***
	.byte 	1     ; *** Load Float 2023754.1175858297 ***
	.dword 	$f70a50f0
	.byte 	$95,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 6.496585 ***
	.dword 	$cfe40639
	.byte 	$83,$0
	.byte 	1     ; *** Load Float -937707.9623680001 ***
	.dword 	$e4eebf65
	.byte 	$94,$80
	.byte 	$2f   ; *** Command / ***
	.byte 	1     ; *** Load Float -6.928153818374466e-06 ***
	.dword 	$e878635d
	.byte 	$6f,$80
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 1.817094162106514e-09 ***
	.dword 	$f9bd512e
	.byte 	$63,$0
	.byte 	1     ; *** Load Float 321657218485962.44 ***
	.dword 	$9245d41f
	.byte 	$b1,$0
	.byte 	$2a   ; *** Command * ***
	.byte 	1     ; *** Load Float 584481.4539102619 ***
	.dword 	$8eb21743
	.byte 	$94,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 487.53 ***
	.dword 	$f3c3d70a
	.byte 	$89,$0
	.byte 	1     ; *** Load Float -9.0 ***
	.dword 	$90000000
	.byte 	$84,$80
	.byte 	$2f   ; *** Command / ***
	.byte 	1     ; *** Load Float -54.169999999999995 ***
	.dword 	$d8ae147a
	.byte 	$86,$80
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 5.0 ***
	.dword 	$a0000000
	.byte 	$83,$0
	.byte 	1     ; *** Load Float 755.49 ***
	.dword 	$bcdf5c28
	.byte 	$8a,$0
	.byte 	$7e   ; *** Command ~ ***
	.byte 	1     ; *** Load Float -1 ***
	.dword 	$80000000
	.byte 	$81,$80
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 5.926742553710937e-06 ***
	.dword 	$c6de54b4
	.byte 	$6f,$0
	.byte 	1     ; *** Load Float 14966728199147.355 ***
	.dword 	$d9cb6848
	.byte 	$ac,$0
	.byte 	$2f   ; *** Command / ***
	.byte 	1     ; *** Load Float 3.9599453366491814e-19 ***
	.dword 	$e9c10084
	.byte 	$43,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float -10.0 ***
	.dword 	$a0000000
	.byte 	$84,$80
	.byte 	1     ; *** Load Float 3.141517 ***
	.dword 	$c90e9d51
	.byte 	$82,$0
	.byte 	$7e   ; *** Command ~ ***
	.byte 	1     ; *** Load Float -1 ***
	.dword 	$80000000
	.byte 	$81,$80
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 12.0 ***
	.dword 	$c0000000
	.byte 	$84,$0
	.byte 	1     ; *** Load Float 677.04 ***
	.dword 	$a9428f5c
	.byte 	$8a,$0
	.byte 	$2a   ; *** Command * ***
	.byte 	1     ; *** Load Float 8124.48 ***
	.dword 	$fde3d70a
	.byte 	$8d,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 4.423587 ***
	.dword 	$8d8e0653
	.byte 	$83,$0
	.byte 	1     ; *** Load Float -33.69 ***
	.dword 	$86c28f5c
	.byte 	$86,$80
	.byte 	$7e   ; *** Command ~ ***
	.byte 	1     ; *** Load Float 1 ***
	.dword 	$80000000
	.byte 	$81,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float -1.8821720004780217e-13 ***
	.dword 	$d3e9ea14
	.byte 	$56,$80
	.byte 	1     ; *** Load Float 17.0 ***
	.dword 	$88000000
	.byte 	$85,$0
	.byte 	$7e   ; *** Command ~ ***
	.byte 	1     ; *** Load Float -1 ***
	.dword 	$80000000
	.byte 	$81,$80
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 10.0 ***
	.dword 	$a0000000
	.byte 	$84,$0
	.byte 	1     ; *** Load Float -9.0 ***
	.dword 	$90000000
	.byte 	$84,$80
	.byte 	$2b   ; *** Command + ***
	.byte 	1     ; *** Load Float 1.0 ***
	.dword 	$80000000
	.byte 	$81,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 9.817292 ***
	.dword 	$9d13a0c6
	.byte 	$84,$0
	.byte 	1     ; *** Load Float -3.0 ***
	.dword 	$c0000000
	.byte 	$82,$80
	.byte 	$2f   ; *** Command / ***
	.byte 	1     ; *** Load Float -3.2724306666666667 ***
	.dword 	$d16f8108
	.byte 	$82,$80
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 672.09 ***
	.dword 	$a805c28f
	.byte 	$8a,$0
	.byte 	1     ; *** Load Float 1.658935 ***
	.dword 	$d457fb69
	.byte 	$81,$0
	.byte 	$2a   ; *** Command * ***
	.byte 	1     ; *** Load Float 1114.95362415 ***
	.dword 	$8b5e8416
	.byte 	$8b,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 1.0109511094924529e-13 ***
	.dword 	$e3a55d1c
	.byte 	$55,$0
	.byte 	1     ; *** Load Float 866818889.613312 ***
	.dword 	$ceaa6d26
	.byte 	$9e,$0
	.byte 	$2a   ; *** Command * ***
	.byte 	1     ; *** Load Float 8.763115181835939e-05 ***
	.dword 	$b7c69dcc
	.byte 	$73,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 737.38 ***
	.dword 	$b85851eb
	.byte 	$8a,$0
	.byte 	1     ; *** Load Float -53328729.86624 ***
	.dword 	$cb6ed677
	.byte 	$9a,$80
	.byte 	$7e   ; *** Command ~ ***
	.byte 	1     ; *** Load Float 1 ***
	.dword 	$80000000
	.byte 	$81,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float -18.0 ***
	.dword 	$90000000
	.byte 	$85,$80
	.byte 	1     ; *** Load Float 5.814967 ***
	.dword 	$ba1435ac
	.byte 	$83,$0
	.byte 	$2d   ; *** Command - ***
	.byte 	1     ; *** Load Float -23.814967 ***
	.dword 	$be850d6b
	.byte 	$85,$80
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float -653.09 ***
	.dword 	$a345c28f
	.byte 	$8a,$80
	.byte 	1     ; *** Load Float -87.82 ***
	.dword 	$afa3d70a
	.byte 	$87,$80
	.byte 	$7e   ; *** Command ~ ***
	.byte 	1     ; *** Load Float -1 ***
	.dword 	$80000000
	.byte 	$81,$80
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float -32015491.530752 ***
	.dword 	$f44241c3
	.byte 	$99,$80
	.byte 	1     ; *** Load Float 0.0 ***
	.dword 	$0
	.byte 	$80,$40
	.byte 	$2a   ; *** Command * ***
	.byte 	1     ; *** Load Float -0.0 ***
	.dword 	$0
	.byte 	$80,$40
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 18.0 ***
	.dword 	$90000000
	.byte 	$85,$0
	.byte 	1     ; *** Load Float 6.928781 ***
	.dword 	$ddb892ee
	.byte 	$83,$0
	.byte 	$7e   ; *** Command ~ ***
	.byte 	1     ; *** Load Float 1 ***
	.dword 	$80000000
	.byte 	$81,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 14.0 ***
	.dword 	$e0000000
	.byte 	$84,$0
	.byte 	1     ; *** Load Float -9312.239615999999 ***
	.dword 	$9180f55d
	.byte 	$8e,$80
	.byte 	$2f   ; *** Command / ***
	.byte 	1     ; *** Load Float -0.0015033977407481695 ***
	.dword 	$c50da842
	.byte 	$77,$80
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float -1.132577017415315e-11 ***
	.dword 	$c73ebbfd
	.byte 	$5c,$80
	.byte 	1     ; *** Load Float 6.779812 ***
	.dword 	$d8f4384b
	.byte 	$83,$0
	.byte 	$2a   ; *** Command * ***
	.byte 	1     ; *** Load Float -7.678659253596561e-11 ***
	.dword 	$a8db0239
	.byte 	$5f,$80
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 1.520676 ***
	.dword 	$c2a582db
	.byte 	$81,$0
	.byte 	1     ; *** Load Float -258863.26784 ***
	.dword 	$fccbd124
	.byte 	$92,$80
	.byte 	$7e   ; *** Command ~ ***
	.byte 	1     ; *** Load Float 1 ***
	.dword 	$80000000
	.byte 	$81,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 8.0 ***
	.dword 	$80000000
	.byte 	$84,$0
	.byte 	1     ; *** Load Float -4.1763996705412866e-11 ***
	.dword 	$b7ae147a
	.byte 	$5e,$80
	.byte 	$2d   ; *** Command - ***
	.byte 	1     ; *** Load Float 8.000000000041764 ***
	.dword 	$80000000
	.byte 	$84,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 0.836381 ***
	.dword 	$d61d10b1
	.byte 	$80,$0
	.byte 	1     ; *** Load Float 189337826448.3758 ***
	.dword 	$b055a7d2
	.byte 	$a6,$0
	.byte 	$7e   ; *** Command ~ ***
	.byte 	1     ; *** Load Float -1 ***
	.dword 	$80000000
	.byte 	$81,$80
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float -1.4106124877929688e-05 ***
	.dword 	$eca95853
	.byte 	$70,$80
	.byte 	1     ; *** Load Float -805.08 ***
	.dword 	$c9451eb8
	.byte 	$8a,$80
	.byte 	$7e   ; *** Command ~ ***
	.byte 	1     ; *** Load Float 1 ***
	.dword 	$80000000
	.byte 	$81,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float -325.84 ***
	.dword 	$a2eb851e
	.byte 	$89,$80
	.byte 	1     ; *** Load Float -325.84 ***
	.dword 	$a2eb851e
	.byte 	$89,$80
	.byte 	$2a   ; *** Command * ***
	.byte 	1     ; *** Load Float 106171.70559999999 ***
	.dword 	$cf5dda51
	.byte 	$91,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 5.262509 ***
	.dword 	$a8667946
	.byte 	$83,$0
	.byte 	1     ; *** Load Float 5.098982 ***
	.dword 	$a32adc4c
	.byte 	$83,$0
	.byte 	$2b   ; *** Command + ***
	.byte 	1     ; *** Load Float 10.361491000000001 ***
	.dword 	$a5c8aac9
	.byte 	$84,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float -159.81 ***
	.dword 	$9fcf5c28
	.byte 	$88,$80
	.byte 	1     ; *** Load Float 7753.760768 ***
	.dword 	$f24e160d
	.byte 	$8d,$0
	.byte 	$2d   ; *** Command - ***
	.byte 	1     ; *** Load Float -7913.5707680000005 ***
	.dword 	$f74c90ee
	.byte 	$8d,$80
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 6.10732 ***
	.dword 	$c36f2a5a
	.byte 	$83,$0
	.byte 	1     ; *** Load Float 45576.093695999996 ***
	.dword 	$b20817fc
	.byte 	$90,$0
	.byte 	$2a   ; *** Command * ***
	.byte 	1     ; *** Load Float 278347.78855145467 ***
	.dword 	$87e9793b
	.byte 	$93,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 3.610687 ***
	.dword 	$e7157eed
	.byte 	$82,$0
	.byte 	1     ; *** Load Float 894.36 ***
	.dword 	$df970a3d
	.byte 	$8a,$0
	.byte 	$2a   ; *** Command * ***
	.byte 	1     ; *** Load Float 3229.25402532 ***
	.dword 	$c9d4107c
	.byte 	$8c,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 9.642219 ***
	.dword 	$9a46876e
	.byte 	$84,$0
	.byte 	1     ; *** Load Float 8.0 ***
	.dword 	$80000000
	.byte 	$84,$0
	.byte 	$2b   ; *** Command + ***
	.byte 	1     ; *** Load Float 17.642219 ***
	.dword 	$8d2343b7
	.byte 	$85,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 4.0 ***
	.dword 	$80000000
	.byte 	$83,$0
	.byte 	1     ; *** Load Float 18.0 ***
	.dword 	$90000000
	.byte 	$85,$0
	.byte 	$7e   ; *** Command ~ ***
	.byte 	1     ; *** Load Float -1 ***
	.dword 	$80000000
	.byte 	$81,$80
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float -19.0 ***
	.dword 	$98000000
	.byte 	$85,$80
	.byte 	1     ; *** Load Float 859.38 ***
	.dword 	$d6d851eb
	.byte 	$8a,$0
	.byte 	$2d   ; *** Command - ***
	.byte 	1     ; *** Load Float -878.38 ***
	.dword 	$db9851eb
	.byte 	$8a,$80
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float -154.36 ***
	.dword 	$9a5c28f5
	.byte 	$88,$80
	.byte 	1     ; *** Load Float -8.0 ***
	.dword 	$80000000
	.byte 	$84,$80
	.byte 	$2b   ; *** Command + ***
	.byte 	1     ; *** Load Float -162.36 ***
	.dword 	$a25c28f5
	.byte 	$88,$80
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float -2.4429755285382272e-11 ***
	.dword 	$d6e2eb1c
	.byte 	$5d,$80
	.byte 	1     ; *** Load Float 220.33 ***
	.dword 	$dc547ae1
	.byte 	$88,$0
	.byte 	$2b   ; *** Command + ***
	.byte 	1     ; *** Load Float 220.32999999997557 ***
	.dword 	$dc547ae1
	.byte 	$88,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float -761.44 ***
	.dword 	$be5c28f5
	.byte 	$8a,$80
	.byte 	1     ; *** Load Float 56573.034496 ***
	.dword 	$dcfd08d4
	.byte 	$90,$0
	.byte 	$2d   ; *** Command - ***
	.byte 	1     ; *** Load Float -57334.474496 ***
	.dword 	$dff67978
	.byte 	$90,$80
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float -17.0 ***
	.dword 	$88000000
	.byte 	$85,$80
	.byte 	1     ; *** Load Float 1370.5154559999999 ***
	.dword 	$ab507e9d
	.byte 	$8b,$0
	.byte 	$2f   ; *** Command / ***
	.byte 	1     ; *** Load Float -0.012404092143270219 ***
	.dword 	$cb3a8885
	.byte 	$7a,$80
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float -19.0 ***
	.dword 	$98000000
	.byte 	$85,$80
	.byte 	1     ; *** Load Float 7.194752 ***
	.dword 	$e63b688b
	.byte 	$83,$0
	.byte 	$2b   ; *** Command + ***
	.byte 	1     ; *** Load Float -11.805247999999999 ***
	.dword 	$bce24bba
	.byte 	$84,$80
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float -9.0 ***
	.dword 	$90000000
	.byte 	$84,$80
	.byte 	1     ; *** Load Float 478.96166400000004 ***
	.dword 	$ef7b17ce
	.byte 	$89,$0
	.byte 	$2a   ; *** Command * ***
	.byte 	1     ; *** Load Float -4310.654976000001 ***
	.dword 	$86b53d64
	.byte 	$8d,$80
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 0.0 ***
	.dword 	$0
	.byte 	$80,$40
	.byte 	1     ; *** Load Float -864.5959680000001 ***
	.dword 	$d8262456
	.byte 	$8a,$80
	.byte 	$2f   ; *** Command / ***
	.byte 	1     ; *** Load Float -0.0 ***
	.dword 	$0
	.byte 	$80,$40
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 1.83072 ***
	.dword 	$ea550870
	.byte 	$81,$0
	.byte 	1     ; *** Load Float -20.0 ***
	.dword 	$a0000000
	.byte 	$85,$80
	.byte 	$2b   ; *** Command + ***
	.byte 	1     ; *** Load Float -18.16928 ***
	.dword 	$915aaf78
	.byte 	$85,$80
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 7.0 ***
	.dword 	$e0000000
	.byte 	$83,$0
	.byte 	1     ; *** Load Float 8.28253 ***
	.dword 	$84853e2d
	.byte 	$84,$0
	.byte 	$2f   ; *** Command / ***
	.byte 	1     ; *** Load Float 0.8451523870121811 ***
	.dword 	$d85be826
	.byte 	$80,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float -491694.587904 ***
	.dword 	$f015d2d0
	.byte 	$93,$80
	.byte 	1     ; *** Load Float -491694.587904 ***
	.dword 	$f015d2d0
	.byte 	$93,$80
	.byte 	$2a   ; *** Command * ***
	.byte 	1     ; *** Load Float 241763567774.0844 ***
	.dword 	$e128ed22
	.byte 	$a6,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 17.0 ***
	.dword 	$88000000
	.byte 	$85,$0
	.byte 	1     ; *** Load Float 19.0 ***
	.dword 	$98000000
	.byte 	$85,$0
	.byte 	$2a   ; *** Command * ***
	.byte 	1     ; *** Load Float 323.0 ***
	.dword 	$a1800000
	.byte 	$89,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 2.0191771909594535e-10 ***
	.dword 	$de02c908
	.byte 	$60,$0
	.byte 	1     ; *** Load Float 9.207502 ***
	.dword 	$9351ed9d
	.byte 	$84,$0
	.byte 	$7e   ; *** Command ~ ***
	.byte 	1     ; *** Load Float -1 ***
	.dword 	$80000000
	.byte 	$81,$80
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float -201.75 ***
	.dword 	$c9c00000
	.byte 	$88,$80
	.byte 	1     ; *** Load Float 16.0 ***
	.dword 	$80000000
	.byte 	$85,$0
	.byte 	$2a   ; *** Command * ***
	.byte 	1     ; *** Load Float -3228.0 ***
	.dword 	$c9c00000
	.byte 	$8c,$80
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 3.304549 ***
	.dword 	$d37dbb16
	.byte 	$82,$0
	.byte 	1     ; *** Load Float 16.09 ***
	.dword 	$80b851eb
	.byte 	$85,$0
	.byte 	$7e   ; *** Command ~ ***
	.byte 	1     ; *** Load Float -1 ***
	.dword 	$80000000
	.byte 	$81,$80
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 12533985880.047615 ***
	.dword 	$bac55c96
	.byte 	$a2,$0
	.byte 	1     ; *** Load Float -14.0 ***
	.dword 	$e0000000
	.byte 	$84,$80
	.byte 	$2d   ; *** Command - ***
	.byte 	1     ; *** Load Float 12533985894.047615 ***
	.dword 	$bac55c99
	.byte 	$a2,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float -16.0 ***
	.dword 	$80000000
	.byte 	$85,$80
	.byte 	1     ; *** Load Float 6.702142 ***
	.dword 	$d677f27f
	.byte 	$83,$0
	.byte 	$2d   ; *** Command - ***
	.byte 	1     ; *** Load Float -22.702142000000002 ***
	.dword 	$b59dfc9f
	.byte 	$85,$80
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 945.66 ***
	.dword 	$ec6a3d70
	.byte 	$8a,$0
	.byte 	1     ; *** Load Float 917.12 ***
	.dword 	$e547ae14
	.byte 	$8a,$0
	.byte 	$7e   ; *** Command ~ ***
	.byte 	1     ; *** Load Float 1 ***
	.dword 	$80000000
	.byte 	$81,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 4.0 ***
	.dword 	$80000000
	.byte 	$83,$0
	.byte 	1     ; *** Load Float 7.68829345703125e-06 ***
	.dword 	$80fcf80d
	.byte 	$70,$0
	.byte 	$2d   ; *** Command - ***
	.byte 	1     ; *** Load Float 3.999992311706543 ***
	.dword 	$ffffdfc0
	.byte 	$82,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float -237.6 ***
	.dword 	$ed999999
	.byte 	$88,$80
	.byte 	1     ; *** Load Float -9.63970947265625e-06 ***
	.dword 	$a1ba3ca7
	.byte 	$70,$80
	.byte 	$2a   ; *** Command * ***
	.byte 	1     ; *** Load Float 0.002290394970703125 ***
	.dword 	$961a737e
	.byte 	$78,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 10.0 ***
	.dword 	$a0000000
	.byte 	$84,$0
	.byte 	1     ; *** Load Float 1.745065 ***
	.dword 	$df5e4a38
	.byte 	$81,$0
	.byte 	$2f   ; *** Command / ***
	.byte 	1     ; *** Load Float 5.730445570795357 ***
	.dword 	$b75fcf63
	.byte 	$83,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float -13.0 ***
	.dword 	$d0000000
	.byte 	$84,$80
	.byte 	1     ; *** Load Float -6.0 ***
	.dword 	$c0000000
	.byte 	$83,$80
	.byte 	$7e   ; *** Command ~ ***
	.byte 	1     ; *** Load Float -1 ***
	.dword 	$80000000
	.byte 	$81,$80
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float -2.7267305995337666e-12 ***
	.dword 	$bfe06961
	.byte 	$5a,$80
	.byte 	1     ; *** Load Float -842.35 ***
	.dword 	$d2966666
	.byte 	$8a,$80
	.byte 	$2d   ; *** Command - ***
	.byte 	1     ; *** Load Float 842.3499999999973 ***
	.dword 	$d2966666
	.byte 	$8a,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 223.31 ***
	.dword 	$df4f5c28
	.byte 	$88,$0
	.byte 	1     ; *** Load Float 223.31 ***
	.dword 	$df4f5c28
	.byte 	$88,$0
	.byte 	$2a   ; *** Command * ***
	.byte 	1     ; *** Load Float 49867.356100000005 ***
	.dword 	$c2cb5b29
	.byte 	$90,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 1.404404 ***
	.dword 	$b3c382a1
	.byte 	$81,$0
	.byte 	1     ; *** Load Float -11.0 ***
	.dword 	$b0000000
	.byte 	$84,$80
	.byte 	$7e   ; *** Command ~ ***
	.byte 	1     ; *** Load Float 1 ***
	.dword 	$80000000
	.byte 	$81,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 8.381134 ***
	.dword 	$86191ff7
	.byte 	$84,$0
	.byte 	1     ; *** Load Float -13020909277332.635 ***
	.dword 	$bd7aaac1
	.byte 	$ac,$80
	.byte 	$2d   ; *** Command - ***
	.byte 	1     ; *** Load Float 13020909277341.016 ***
	.dword 	$bd7aaac1
	.byte 	$ac,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 4.345937 ***
	.dword 	$8b11ea78
	.byte 	$83,$0
	.byte 	1     ; *** Load Float 655761928945.1396 ***
	.dword 	$98ae74f2
	.byte 	$a8,$0
	.byte 	$2f   ; *** Command / ***
	.byte 	1     ; *** Load Float 6.627309101324143e-12 ***
	.dword 	$e92d7e5c
	.byte 	$5b,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 16.0 ***
	.dword 	$80000000
	.byte 	$85,$0
	.byte 	1     ; *** Load Float -7.830667495727539e-07 ***
	.dword 	$d233eff1
	.byte 	$6c,$80
	.byte 	$2d   ; *** Command - ***
	.byte 	1     ; *** Load Float 16.00000078306675 ***
	.dword 	$80000069
	.byte 	$85,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float -1.8768453598022463e-07 ***
	.dword 	$c9865519
	.byte 	$6a,$80
	.byte 	1     ; *** Load Float -1142411908.612096 ***
	.dword 	$882fa509
	.byte 	$9f,$80
	.byte 	$7e   ; *** Command ~ ***
	.byte 	1     ; *** Load Float 1 ***
	.dword 	$80000000
	.byte 	$81,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float -2.0172130632545306e-16 ***
	.dword 	$e8919ef9
	.byte 	$4c,$80
	.byte 	1     ; *** Load Float 1.250733 ***
	.dword 	$a01804d9
	.byte 	$81,$0
	.byte 	$2b   ; *** Command + ***
	.byte 	1     ; *** Load Float 1.2507329999999999 ***
	.dword 	$a01804d9
	.byte 	$81,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float -1108460843185538.6 ***
	.dword 	$fc08e9b3
	.byte 	$b2,$80
	.byte 	1     ; *** Load Float -4.6733475755900144e-14 ***
	.dword 	$d2780778
	.byte 	$54,$80
	.byte 	$2a   ; *** Command * ***
	.byte 	1     ; *** Load Float 51.802227941376 ***
	.dword 	$cf357b3d
	.byte 	$86,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float -499.02 ***
	.dword 	$f9828f5c
	.byte 	$89,$80
	.byte 	1     ; *** Load Float 951.04 ***
	.dword 	$edc28f5c
	.byte 	$8a,$0
	.byte 	$2a   ; *** Command * ***
	.byte 	1     ; *** Load Float -474587.98079999996 ***
	.dword 	$e7bb7f62
	.byte 	$93,$80
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float -11.0 ***
	.dword 	$b0000000
	.byte 	$84,$80
	.byte 	1     ; *** Load Float 1.0 ***
	.dword 	$80000000
	.byte 	$81,$0
	.byte 	$2b   ; *** Command + ***
	.byte 	1     ; *** Load Float -10.0 ***
	.dword 	$a0000000
	.byte 	$84,$80
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 292.57 ***
	.dword 	$9248f5c2
	.byte 	$89,$0
	.byte 	1     ; *** Load Float 217.6 ***
	.dword 	$d9999999
	.byte 	$88,$0
	.byte 	$7e   ; *** Command ~ ***
	.byte 	1     ; *** Load Float 1 ***
	.dword 	$80000000
	.byte 	$81,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 13.0 ***
	.dword 	$d0000000
	.byte 	$84,$0
	.byte 	1     ; *** Load Float 3.963962 ***
	.dword 	$fdb18dac
	.byte 	$82,$0
	.byte 	$2b   ; *** Command + ***
	.byte 	1     ; *** Load Float 16.963962 ***
	.dword 	$87b631b5
	.byte 	$85,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float -3.0 ***
	.dword 	$c0000000
	.byte 	$82,$80
	.byte 	1     ; *** Load Float 941.6 ***
	.dword 	$eb666666
	.byte 	$8a,$0
	.byte 	$2b   ; *** Command + ***
	.byte 	1     ; *** Load Float 938.6 ***
	.dword 	$eaa66666
	.byte 	$8a,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 16.0 ***
	.dword 	$80000000
	.byte 	$85,$0
	.byte 	1     ; *** Load Float 16.0 ***
	.dword 	$80000000
	.byte 	$85,$0
	.byte 	$2b   ; *** Command + ***
	.byte 	1     ; *** Load Float 32.0 ***
	.dword 	$80000000
	.byte 	$86,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 8.4552978515625e-05 ***
	.dword 	$b15208e1
	.byte 	$73,$0
	.byte 	1     ; *** Load Float -483.37 ***
	.dword 	$f1af5c28
	.byte 	$89,$80
	.byte 	$2f   ; *** Command / ***
	.byte 	1     ; *** Load Float -1.7492392683787783e-07 ***
	.dword 	$bbd2b90e
	.byte 	$6a,$80
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 0.380461 ***
	.dword 	$c2cbc8c0
	.byte 	$7f,$0
	.byte 	1     ; *** Load Float -1163265710000.9636 ***
	.dword 	$876c050b
	.byte 	$a9,$80
	.byte 	$2f   ; *** Command / ***
	.byte 	1     ; *** Load Float -3.2706285135808294e-13 ***
	.dword 	$b81eb96e
	.byte 	$57,$80
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 3.121194 ***
	.dword 	$c7c1a47a
	.byte 	$82,$0
	.byte 	1     ; *** Load Float -764.76 ***
	.dword 	$bf30a3d7
	.byte 	$8a,$80
	.byte 	$2a   ; *** Command * ***
	.byte 	1     ; *** Load Float -2386.96432344 ***
	.dword 	$952f6dde
	.byte 	$8c,$80
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float -898.75 ***
	.dword 	$e0b00000
	.byte 	$8a,$80
	.byte 	1     ; *** Load Float -407884825801458.2 ***
	.dword 	$b97c0b13
	.byte 	$b1,$80
	.byte 	$2d   ; *** Command - ***
	.byte 	1     ; *** Load Float 407884825800559.44 ***
	.dword 	$b97c0b13
	.byte 	$b1,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 14.0 ***
	.dword 	$e0000000
	.byte 	$84,$0
	.byte 	1     ; *** Load Float 5.0 ***
	.dword 	$a0000000
	.byte 	$83,$0
	.byte 	$7e   ; *** Command ~ ***
	.byte 	1     ; *** Load Float 1 ***
	.dword 	$80000000
	.byte 	$81,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 246.82 ***
	.dword 	$f6d1eb85
	.byte 	$88,$0
	.byte 	1     ; *** Load Float 8.013703336473554e-13 ***
	.dword 	$e190d173
	.byte 	$58,$0
	.byte 	$2f   ; *** Command / ***
	.byte 	1     ; *** Load Float 307997425954893.94 ***
	.dword 	$8c0f9e95
	.byte 	$b1,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 3.0 ***
	.dword 	$c0000000
	.byte 	$82,$0
	.byte 	1     ; *** Load Float 203738405115.265 ***
	.dword 	$bdbf0563
	.byte 	$a6,$0
	.byte 	$2a   ; *** Command * ***
	.byte 	1     ; *** Load Float 611215215345.795 ***
	.dword 	$8e4f440a
	.byte 	$a8,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float -1.1661541066132486e-12 ***
	.dword 	$a41f212d
	.byte 	$59,$80
	.byte 	1     ; *** Load Float 0.609409 ***
	.dword 	$9c023a6c
	.byte 	$80,$0
	.byte 	$2b   ; *** Command + ***
	.byte 	1     ; *** Load Float 0.6094089999988338 ***
	.dword 	$9c023a6c
	.byte 	$80,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 6.041389 ***
	.dword 	$c1530f06
	.byte 	$83,$0
	.byte 	1     ; *** Load Float 71188962259798.84 ***
	.dword 	$817df19d
	.byte 	$af,$0
	.byte 	$2a   ; *** Command * ***
	.byte 	1     ; *** Load Float 430080213517763.9 ***
	.dword 	$c393ed2d
	.byte 	$b1,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 2.586457270581377e-15 ***
	.dword 	$ba5fb71f
	.byte 	$50,$0
	.byte 	1     ; *** Load Float 3.71792702935636e-11 ***
	.dword 	$a384230f
	.byte 	$5e,$0
	.byte 	$2a   ; *** Command * ***
	.byte 	1     ; *** Load Float 9.616259396569779e-26 ***
	.dword 	$ee1648f4
	.byte 	$2d,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float -19.0 ***
	.dword 	$98000000
	.byte 	$85,$80
	.byte 	1     ; *** Load Float 19.0 ***
	.dword 	$98000000
	.byte 	$85,$0
	.byte 	$2b   ; *** Command + ***
	.byte 	1     ; *** Load Float 0.0 ***
	.dword 	$0
	.byte 	$80,$40
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 337.3 ***
	.dword 	$a8a66666
	.byte 	$89,$0
	.byte 	1     ; *** Load Float -13.0 ***
	.dword 	$d0000000
	.byte 	$84,$80
	.byte 	$2d   ; *** Command - ***
	.byte 	1     ; *** Load Float 350.3 ***
	.dword 	$af266666
	.byte 	$89,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float -8.376218829653227e-15 ***
	.dword 	$96e47dc3
	.byte 	$52,$80
	.byte 	1     ; *** Load Float -5.941975116729736e-08 ***
	.dword 	$ff34b513
	.byte 	$68,$80
	.byte 	$7e   ; *** Command ~ ***
	.byte 	1     ; *** Load Float 1 ***
	.dword 	$80000000
	.byte 	$81,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 539.2 ***
	.dword 	$86cccccc
	.byte 	$8a,$0
	.byte 	1     ; *** Load Float 376126392.23808 ***
	.dword 	$b359ddc1
	.byte 	$9d,$0
	.byte 	$7e   ; *** Command ~ ***
	.byte 	1     ; *** Load Float -1 ***
	.dword 	$80000000
	.byte 	$81,$80
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 15.0 ***
	.dword 	$f0000000
	.byte 	$84,$0
	.byte 	1     ; *** Load Float 17.0 ***
	.dword 	$88000000
	.byte 	$85,$0
	.byte 	$2a   ; *** Command * ***
	.byte 	1     ; *** Load Float 255.0 ***
	.dword 	$ff000000
	.byte 	$88,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 4.158243536949158e-09 ***
	.dword 	$8ee04c05
	.byte 	$65,$0
	.byte 	1     ; *** Load Float 1.190604 ***
	.dword 	$9865b63d
	.byte 	$81,$0
	.byte 	$2a   ; *** Command * ***
	.byte 	1     ; *** Load Float 4.950821388065815e-09 ***
	.dword 	$aa1be2ad
	.byte 	$65,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float -443.21 ***
	.dword 	$dd9ae147
	.byte 	$89,$80
	.byte 	1     ; *** Load Float -3.962362825404853e-12 ***
	.dword 	$8b69ca9e
	.byte 	$5b,$80
	.byte 	$2f   ; *** Command / ***
	.byte 	1     ; *** Load Float 111854976318256.56 ***
	.dword 	$cb768842
	.byte 	$af,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float -5.026038252253784e-15 ***
	.dword 	$b515054a
	.byte 	$51,$80
	.byte 	1     ; *** Load Float -1247857736595.5378 ***
	.dword 	$91450efd
	.byte 	$a9,$80
	.byte 	$7e   ; *** Command ~ ***
	.byte 	1     ; *** Load Float 1 ***
	.dword 	$80000000
	.byte 	$81,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 0.082103 ***
	.dword 	$a8259e1f
	.byte 	$7d,$0
	.byte 	1     ; *** Load Float -17.0 ***
	.dword 	$88000000
	.byte 	$85,$80
	.byte 	$2a   ; *** Command * ***
	.byte 	1     ; *** Load Float -1.395751 ***
	.dword 	$b2a7f801
	.byte 	$81,$80
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 126.14 ***
	.dword 	$fc47ae14
	.byte 	$87,$0
	.byte 	1     ; *** Load Float 1.2433019946911373e-13 ***
	.dword 	$8bfbbd7b
	.byte 	$56,$0
	.byte 	$7e   ; *** Command ~ ***
	.byte 	1     ; *** Load Float 1 ***
	.dword 	$80000000
	.byte 	$81,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 1.286333 ***
	.dword 	$a4a68f4b
	.byte 	$81,$0
	.byte 	1     ; *** Load Float 0.0 ***
	.dword 	$0
	.byte 	$80,$40
	.byte 	$2d   ; *** Command - ***
	.byte 	1     ; *** Load Float 1.286333 ***
	.dword 	$a4a68f4b
	.byte 	$81,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 6.361007690429688e-10 ***
	.dword 	$aed99cbe
	.byte 	$62,$0
	.byte 	1     ; *** Load Float 6.361007690429688e-10 ***
	.dword 	$aed99cbe
	.byte 	$62,$0
	.byte 	$2f   ; *** Command / ***
	.byte 	1     ; *** Load Float 1.0 ***
	.dword 	$80000000
	.byte 	$81,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 9.434051 ***
	.dword 	$96f1df76
	.byte 	$84,$0
	.byte 	1     ; *** Load Float 4.871488 ***
	.dword 	$9be33acd
	.byte 	$83,$0
	.byte 	$2b   ; *** Command + ***
	.byte 	1     ; *** Load Float 14.305539 ***
	.dword 	$e4e37cdc
	.byte 	$84,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float -2.718821633607149e-12 ***
	.dword 	$bf51efb6
	.byte 	$5a,$80
	.byte 	1     ; *** Load Float 20.0 ***
	.dword 	$a0000000
	.byte 	$85,$0
	.byte 	$2b   ; *** Command + ***
	.byte 	1     ; *** Load Float 19.999999999997282 ***
	.dword 	$9fffffff
	.byte 	$85,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float -555.88 ***
	.dword 	$8af851eb
	.byte 	$8a,$80
	.byte 	1     ; *** Load Float -555.88 ***
	.dword 	$8af851eb
	.byte 	$8a,$80
	.byte 	$2a   ; *** Command * ***
	.byte 	1     ; *** Load Float 309002.5744 ***
	.dword 	$96e15261
	.byte 	$93,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float -9.0 ***
	.dword 	$90000000
	.byte 	$84,$80
	.byte 	1     ; *** Load Float -12.0 ***
	.dword 	$c0000000
	.byte 	$84,$80
	.byte 	$2a   ; *** Command * ***
	.byte 	1     ; *** Load Float 108.0 ***
	.dword 	$d8000000
	.byte 	$87,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float -301.72 ***
	.dword 	$96dc28f5
	.byte 	$89,$80
	.byte 	1     ; *** Load Float -24241856447344.805 ***
	.dword 	$b061f9f0
	.byte 	$ad,$80
	.byte 	$7e   ; *** Command ~ ***
	.byte 	1     ; *** Load Float 1 ***
	.dword 	$80000000
	.byte 	$81,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 0.147095 ***
	.dword 	$96a01259
	.byte 	$7e,$0
	.byte 	1     ; *** Load Float 6.299646 ***
	.dword 	$c996b335
	.byte 	$83,$0
	.byte 	$2a   ; *** Command * ***
	.byte 	1     ; *** Load Float 0.92664642837 ***
	.dword 	$ed38b348
	.byte 	$80,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float -19.0 ***
	.dword 	$98000000
	.byte 	$85,$80
	.byte 	1     ; *** Load Float -19.0 ***
	.dword 	$98000000
	.byte 	$85,$80
	.byte 	$2b   ; *** Command + ***
	.byte 	1     ; *** Load Float -38.0 ***
	.dword 	$98000000
	.byte 	$86,$80
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float -3.0 ***
	.dword 	$c0000000
	.byte 	$82,$80
	.byte 	1     ; *** Load Float -16.0 ***
	.dword 	$80000000
	.byte 	$85,$80
	.byte 	$2a   ; *** Command * ***
	.byte 	1     ; *** Load Float 48.0 ***
	.dword 	$c0000000
	.byte 	$86,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 25930.170368 ***
	.dword 	$ca94573a
	.byte 	$8f,$0
	.byte 	1     ; *** Load Float 0.0 ***
	.dword 	$0
	.byte 	$80,$40
	.byte 	$2a   ; *** Command * ***
	.byte 	1     ; *** Load Float 0.0 ***
	.dword 	$0
	.byte 	$80,$40
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float -0.925127 ***
	.dword 	$ecd51f81
	.byte 	$80,$80
	.byte 	1     ; *** Load Float 0.063411 ***
	.dword 	$81dda059
	.byte 	$7d,$0
	.byte 	$7e   ; *** Command ~ ***
	.byte 	1     ; *** Load Float -1 ***
	.dword 	$80000000
	.byte 	$81,$80
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 1077946906220.4293 ***
	.dword 	$fafaa476
	.byte 	$a8,$0
	.byte 	1     ; *** Load Float 1077946906220.4293 ***
	.dword 	$fafaa476
	.byte 	$a8,$0
	.byte 	$2d   ; *** Command - ***
	.byte 	1     ; *** Load Float 0.0 ***
	.dword 	$0
	.byte 	$80,$40
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 3.7 ***
	.dword 	$eccccccc
	.byte 	$82,$0
	.byte 	1     ; *** Load Float 990.49 ***
	.dword 	$f79f5c28
	.byte 	$8a,$0
	.byte 	$7e   ; *** Command ~ ***
	.byte 	1     ; *** Load Float -1 ***
	.dword 	$80000000
	.byte 	$81,$80
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 26219668.045824 ***
	.dword 	$c80a4a05
	.byte 	$99,$0
	.byte 	1     ; *** Load Float 9.291694 ***
	.dword 	$94aac753
	.byte 	$84,$0
	.byte 	$2f   ; *** Command / ***
	.byte 	1     ; *** Load Float 2821839.38104548 ***
	.dword 	$ac3b3d86
	.byte 	$96,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 9.606788 ***
	.dword 	$99b56755
	.byte 	$84,$0
	.byte 	1     ; *** Load Float 8.632249 ***
	.dword 	$8a1db120
	.byte 	$84,$0
	.byte 	$2a   ; *** Command * ***
	.byte 	1     ; *** Load Float 82.928186106212 ***
	.dword 	$a5db3b35
	.byte 	$87,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 573.5 ***
	.dword 	$8f600000
	.byte 	$8a,$0
	.byte 	1     ; *** Load Float 96.02 ***
	.dword 	$c00a3d70
	.byte 	$87,$0
	.byte 	$2a   ; *** Command * ***
	.byte 	1     ; *** Load Float 55067.47 ***
	.dword 	$d71b7851
	.byte 	$90,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float -897.57 ***
	.dword 	$e0647ae1
	.byte 	$8a,$80
	.byte 	1     ; *** Load Float 3885867606606.873 ***
	.dword 	$e22ff088
	.byte 	$aa,$0
	.byte 	$2d   ; *** Command - ***
	.byte 	1     ; *** Load Float -3885867607504.443 ***
	.dword 	$e22ff089
	.byte 	$aa,$80
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float -11.0 ***
	.dword 	$b0000000
	.byte 	$84,$80
	.byte 	1     ; *** Load Float 305.82 ***
	.dword 	$98e8f5c2
	.byte 	$89,$0
	.byte 	$2d   ; *** Command - ***
	.byte 	1     ; *** Load Float -316.82 ***
	.dword 	$9e68f5c2
	.byte 	$89,$80
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 32781423786.065918 ***
	.dword 	$f43d9a95
	.byte 	$a3,$0
	.byte 	1     ; *** Load Float -14.0 ***
	.dword 	$e0000000
	.byte 	$84,$80
	.byte 	$2b   ; *** Command + ***
	.byte 	1     ; *** Load Float 32781423772.065918 ***
	.dword 	$f43d9a93
	.byte 	$a3,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float -174.88 ***
	.dword 	$aee147ae
	.byte 	$88,$80
	.byte 	1     ; *** Load Float -6.111022949218749e-06 ***
	.dword 	$cd0d4994
	.byte 	$6f,$80
	.byte 	$2f   ; *** Command / ***
	.byte 	1     ; *** Load Float 28617140.117655285 ***
	.dword 	$da54da0f
	.byte 	$99,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 2.00553 ***
	.dword 	$805a9a80
	.byte 	$82,$0
	.byte 	1     ; *** Load Float 4.070846 ***
	.dword 	$82445ed4
	.byte 	$83,$0
	.byte 	$7e   ; *** Command ~ ***
	.byte 	1     ; *** Load Float -1 ***
	.dword 	$80000000
	.byte 	$81,$80
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float -9.0 ***
	.dword 	$90000000
	.byte 	$84,$80
	.byte 	1     ; *** Load Float 0.0 ***
	.dword 	$0
	.byte 	$80,$40
	.byte 	$2b   ; *** Command + ***
	.byte 	1     ; *** Load Float -9.0 ***
	.dword 	$90000000
	.byte 	$84,$80
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 8.363034 ***
	.dword 	$85cefcbd
	.byte 	$84,$0
	.byte 	1     ; *** Load Float 7.407844 ***
	.dword 	$ed0d0edc
	.byte 	$83,$0
	.byte 	$7e   ; *** Command ~ ***
	.byte 	1     ; *** Load Float 1 ***
	.dword 	$80000000
	.byte 	$81,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float -3.743577003479004e-07 ***
	.dword 	$c8fb549f
	.byte 	$6b,$80
	.byte 	1     ; *** Load Float 5.0 ***
	.dword 	$a0000000
	.byte 	$83,$0
	.byte 	$7e   ; *** Command ~ ***
	.byte 	1     ; *** Load Float -1 ***
	.dword 	$80000000
	.byte 	$81,$80
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 2075.099136 ***
	.dword 	$81b1960f
	.byte 	$8c,$0
	.byte 	1     ; *** Load Float -6899091866.910721 ***
	.dword 	$cd9be4cd
	.byte 	$a1,$80
	.byte 	$2a   ; *** Command * ***
	.byte 	1     ; *** Load Float -14316299572211.062 ***
	.dword 	$d0545f35
	.byte 	$ac,$80
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float -870.49 ***
	.dword 	$d99f5c28
	.byte 	$8a,$80
	.byte 	1     ; *** Load Float 0.00042331249999999997 ***
	.dword 	$ddf00abf
	.byte 	$75,$0
	.byte 	$2f   ; *** Command / ***
	.byte 	1     ; *** Load Float -2056376.790196368 ***
	.dword 	$fb05c652
	.byte 	$95,$80
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 3.829273 ***
	.dword 	$f512cf0f
	.byte 	$82,$0
	.byte 	1     ; *** Load Float -190.4 ***
	.dword 	$be666666
	.byte 	$88,$80
	.byte 	$2f   ; *** Command / ***
	.byte 	1     ; *** Load Float -0.02011172794117647 ***
	.dword 	$a4c159b8
	.byte 	$7b,$80
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 32638328.897536002 ***
	.dword 	$f902bc72
	.byte 	$99,$0
	.byte 	1     ; *** Load Float -6.002397537231445e-07 ***
	.dword 	$a120296b
	.byte 	$6c,$80
	.byte 	$2d   ; *** Command - ***
	.byte 	1     ; *** Load Float 32638328.897536602 ***
	.dword 	$f902bc72
	.byte 	$99,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 9.303656 ***
	.dword 	$94dbc664
	.byte 	$84,$0
	.byte 	1     ; *** Load Float -788.76 ***
	.dword 	$c530a3d7
	.byte 	$8a,$80
	.byte 	$2a   ; *** Command * ***
	.byte 	1     ; *** Load Float -7338.35170656 ***
	.dword 	$e552d04b
	.byte 	$8d,$80
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 254.09 ***
	.dword 	$fe170a3d
	.byte 	$88,$0
	.byte 	1     ; *** Load Float -144.09 ***
	.dword 	$90170a3d
	.byte 	$88,$80
	.byte 	$2a   ; *** Command * ***
	.byte 	1     ; *** Load Float -36611.8281 ***
	.dword 	$8f03d3fe
	.byte 	$90,$80
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 0.873371 ***
	.dword 	$df953dea
	.byte 	$80,$0
	.byte 	1     ; *** Load Float 233.96 ***
	.dword 	$e9f5c28f
	.byte 	$88,$0
	.byte 	$2f   ; *** Command / ***
	.byte 	1     ; *** Load Float 0.003732992819285348 ***
	.dword 	$f4a53a13
	.byte 	$78,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 581.86 ***
	.dword 	$91770a3d
	.byte 	$8a,$0
	.byte 	1     ; *** Load Float 4.146044375374913e-12 ***
	.dword 	$91e03f70
	.byte 	$5b,$0
	.byte 	$2b   ; *** Command + ***
	.byte 	1     ; *** Load Float 581.8600000000041 ***
	.dword 	$91770a3d
	.byte 	$8a,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float -0.251604 ***
	.dword 	$80d23d4f
	.byte 	$7f,$80
	.byte 	1     ; *** Load Float -636.9 ***
	.dword 	$9f399999
	.byte 	$8a,$80
	.byte 	$2d   ; *** Command - ***
	.byte 	1     ; *** Load Float 636.6483959999999 ***
	.dword 	$9f297f51
	.byte 	$8a,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float -6546.505728 ***
	.dword 	$cc940bbb
	.byte 	$8d,$80
	.byte 	1     ; *** Load Float 5.26692360836023e-14 ***
	.dword 	$ed337eb2
	.byte 	$54,$0
	.byte 	$2f   ; *** Command / ***
	.byte 	1     ; *** Load Float -1.242946777813272e+17 ***
	.dword 	$dccaacea
	.byte 	$b9,$80
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 13.0 ***
	.dword 	$d0000000
	.byte 	$84,$0
	.byte 	1     ; *** Load Float 7.26825 ***
	.dword 	$e8958106
	.byte 	$83,$0
	.byte 	$2b   ; *** Command + ***
	.byte 	1     ; *** Load Float 20.268250000000002 ***
	.dword 	$a2256041
	.byte 	$85,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 2.45301 ***
	.dword 	$9cfe1da7
	.byte 	$82,$0
	.byte 	1     ; *** Load Float -693.88 ***
	.dword 	$ad7851eb
	.byte 	$8a,$80
	.byte 	$2d   ; *** Command - ***
	.byte 	1     ; *** Load Float 696.33301 ***
	.dword 	$ae155009
	.byte 	$8a,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 6.0 ***
	.dword 	$c0000000
	.byte 	$83,$0
	.byte 	1     ; *** Load Float -1.0 ***
	.dword 	$80000000
	.byte 	$81,$80
	.byte 	$2f   ; *** Command / ***
	.byte 	1     ; *** Load Float -6.0 ***
	.dword 	$c0000000
	.byte 	$83,$80
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 7402.389504 ***
	.dword 	$e7531db4
	.byte 	$8d,$0
	.byte 	1     ; *** Load Float 16.0 ***
	.dword 	$80000000
	.byte 	$85,$0
	.byte 	$2f   ; *** Command / ***
	.byte 	1     ; *** Load Float 462.649344 ***
	.dword 	$e7531db4
	.byte 	$89,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float -123.46 ***
	.dword 	$f6eb851e
	.byte 	$87,$80
	.byte 	1     ; *** Load Float 6.344197 ***
	.dword 	$cb03a96d
	.byte 	$83,$0
	.byte 	$7e   ; *** Command ~ ***
	.byte 	1     ; *** Load Float -1 ***
	.dword 	$80000000
	.byte 	$81,$80
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 382.05 ***
	.dword 	$bf066666
	.byte 	$89,$0
	.byte 	1     ; *** Load Float 9.0 ***
	.dword 	$90000000
	.byte 	$84,$0
	.byte 	$2d   ; *** Command - ***
	.byte 	1     ; *** Load Float 373.05 ***
	.dword 	$ba866666
	.byte 	$89,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 13.0 ***
	.dword 	$d0000000
	.byte 	$84,$0
	.byte 	1     ; *** Load Float 13.0 ***
	.dword 	$d0000000
	.byte 	$84,$0
	.byte 	$7e   ; *** Command ~ ***
	.byte 	1     ; *** Load Float 0 ***
	.dword 	$0
	.byte 	$80,$40
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 20.0 ***
	.dword 	$a0000000
	.byte 	$85,$0
	.byte 	1     ; *** Load Float 8.17364 ***
	.dword 	$82c73abc
	.byte 	$84,$0
	.byte 	$7e   ; *** Command ~ ***
	.byte 	1     ; *** Load Float 1 ***
	.dword 	$80000000
	.byte 	$81,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 1.61815 ***
	.dword 	$cf1f8a09
	.byte 	$81,$0
	.byte 	1     ; *** Load Float 7.67 ***
	.dword 	$f570a3d7
	.byte 	$83,$0
	.byte 	$7e   ; *** Command ~ ***
	.byte 	1     ; *** Load Float -1 ***
	.dword 	$80000000
	.byte 	$81,$80
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 2.058617 ***
	.dword 	$83c06184
	.byte 	$82,$0
	.byte 	1     ; *** Load Float 2.7211666107177734e-08 ***
	.dword 	$e9bf162a
	.byte 	$67,$0
	.byte 	$7e   ; *** Command ~ ***
	.byte 	1     ; *** Load Float 1 ***
	.dword 	$80000000
	.byte 	$81,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float -3.0 ***
	.dword 	$c0000000
	.byte 	$82,$80
	.byte 	1     ; *** Load Float -18.0 ***
	.dword 	$90000000
	.byte 	$85,$80
	.byte 	$2a   ; *** Command * ***
	.byte 	1     ; *** Load Float 54.0 ***
	.dword 	$d8000000
	.byte 	$86,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 20.0 ***
	.dword 	$a0000000
	.byte 	$85,$0
	.byte 	1     ; *** Load Float 381.3 ***
	.dword 	$bea66666
	.byte 	$89,$0
	.byte 	$7e   ; *** Command ~ ***
	.byte 	1     ; *** Load Float -1 ***
	.dword 	$80000000
	.byte 	$81,$80
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 7.61723 ***
	.dword 	$f3c05921
	.byte 	$83,$0
	.byte 	1     ; *** Load Float -9.0 ***
	.dword 	$90000000
	.byte 	$84,$80
	.byte 	$2d   ; *** Command - ***
	.byte 	1     ; *** Load Float 16.61723 ***
	.dword 	$84f01648
	.byte 	$85,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 930.56 ***
	.dword 	$e8a3d70a
	.byte 	$8a,$0
	.byte 	1     ; *** Load Float 312.02 ***
	.dword 	$9c028f5c
	.byte 	$89,$0
	.byte 	$2a   ; *** Command * ***
	.byte 	1     ; *** Load Float 290353.33119999996 ***
	.dword 	$8dc62a99
	.byte 	$93,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 7.999398 ***
	.dword 	$fffb1183
	.byte 	$83,$0
	.byte 	1     ; *** Load Float 9.425957614439539e-14 ***
	.dword 	$d440f238
	.byte 	$55,$0
	.byte 	$7e   ; *** Command ~ ***
	.byte 	1     ; *** Load Float 1 ***
	.dword 	$80000000
	.byte 	$81,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 4.259124398231506e-09 ***
	.dword 	$9257a786
	.byte 	$65,$0
	.byte 	1     ; *** Load Float -719.45 ***
	.dword 	$b3dccccc
	.byte 	$8a,$80
	.byte 	$2f   ; *** Command / ***
	.byte 	1     ; *** Load Float -5.919972754509009e-12 ***
	.dword 	$d04a5fca
	.byte 	$5b,$80
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 1.157927 ***
	.dword 	$9436f3b2
	.byte 	$81,$0
	.byte 	1     ; *** Load Float 775.44 ***
	.dword 	$c1dc28f5
	.byte 	$8a,$0
	.byte 	$2a   ; *** Command * ***
	.byte 	1     ; *** Load Float 897.90291288 ***
	.dword 	$e079c953
	.byte 	$8a,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float -26.96 ***
	.dword 	$d7ae147a
	.byte 	$85,$80
	.byte 	1     ; *** Load Float 9.0 ***
	.dword 	$90000000
	.byte 	$84,$0
	.byte 	$2b   ; *** Command + ***
	.byte 	1     ; *** Load Float -17.96 ***
	.dword 	$8fae147a
	.byte 	$85,$80
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float -435.74 ***
	.dword 	$d9deb851
	.byte 	$89,$80
	.byte 	1     ; *** Load Float 832.78 ***
	.dword 	$d031eb85
	.byte 	$8a,$0
	.byte 	$2f   ; *** Command / ***
	.byte 	1     ; *** Load Float -0.5232354283244074 ***
	.dword 	$85f2c1cc
	.byte 	$80,$80
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float -3.0 ***
	.dword 	$c0000000
	.byte 	$82,$80
	.byte 	1     ; *** Load Float 1.9618797302246096e-06 ***
	.dword 	$83a8d64d
	.byte 	$6e,$0
	.byte 	$2a   ; *** Command * ***
	.byte 	1     ; *** Load Float -5.885639190673828e-06 ***
	.dword 	$c57d4174
	.byte 	$6f,$80
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 0.0 ***
	.dword 	$0
	.byte 	$80,$40
	.byte 	1     ; *** Load Float 687.24 ***
	.dword 	$abcf5c28
	.byte 	$8a,$0
	.byte 	$2d   ; *** Command - ***
	.byte 	1     ; *** Load Float -687.24 ***
	.dword 	$abcf5c28
	.byte 	$8a,$80
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 703.59 ***
	.dword 	$afe5c28f
	.byte 	$8a,$0
	.byte 	1     ; *** Load Float -388.95 ***
	.dword 	$c2799999
	.byte 	$89,$80
	.byte 	$2b   ; *** Command + ***
	.byte 	1     ; *** Load Float 314.64000000000004 ***
	.dword 	$9d51eb85
	.byte 	$89,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 512632360684608.25 ***
	.dword 	$e91e42e1
	.byte 	$b1,$0
	.byte 	1     ; *** Load Float 5.974832 ***
	.dword 	$bf31d2e0
	.byte 	$83,$0
	.byte 	$2d   ; *** Command - ***
	.byte 	1     ; *** Load Float 512632360684602.25 ***
	.dword 	$e91e42e1
	.byte 	$b1,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float -70.28 ***
	.dword 	$8c8f5c28
	.byte 	$87,$80
	.byte 	1     ; *** Load Float 3.433341 ***
	.dword 	$dbbbdbe3
	.byte 	$82,$0
	.byte 	$2d   ; *** Command - ***
	.byte 	1     ; *** Load Float -73.713341 ***
	.dword 	$936d3b08
	.byte 	$87,$80
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float -0.00011454931640625 ***
	.dword 	$f03a322a
	.byte 	$73,$80
	.byte 	1     ; *** Load Float 2.1041046238678972e-13 ***
	.dword 	$ece6afcc
	.byte 	$56,$0
	.byte 	$2a   ; *** Command * ***
	.byte 	1     ; *** Load Float -2.410237463112974e-17 ***
	.dword 	$de4e1f80
	.byte 	$49,$80
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float -155.83 ***
	.dword 	$9bd47ae1
	.byte 	$88,$80
	.byte 	1     ; *** Load Float 297.63 ***
	.dword 	$94d0a3d7
	.byte 	$89,$0
	.byte 	$2d   ; *** Command - ***
	.byte 	1     ; *** Load Float -453.46000000000004 ***
	.dword 	$e2bae147
	.byte 	$89,$80
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float -9.0 ***
	.dword 	$90000000
	.byte 	$84,$80
	.byte 	1     ; *** Load Float -130469.46201599999 ***
	.dword 	$fed2bb23
	.byte 	$91,$80
	.byte 	$7e   ; *** Command ~ ***
	.byte 	1     ; *** Load Float 1 ***
	.dword 	$80000000
	.byte 	$81,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float -579.24 ***
	.dword 	$90cf5c28
	.byte 	$8a,$80
	.byte 	1     ; *** Load Float -18.0 ***
	.dword 	$90000000
	.byte 	$85,$80
	.byte 	$2d   ; *** Command - ***
	.byte 	1     ; *** Load Float -561.24 ***
	.dword 	$8c4f5c28
	.byte 	$8a,$80
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 2.472037 ***
	.dword 	$9e35daad
	.byte 	$82,$0
	.byte 	1     ; *** Load Float 1497.1494400000001 ***
	.dword 	$bb24c836
	.byte 	$8b,$0
	.byte 	$7e   ; *** Command ~ ***
	.byte 	1     ; *** Load Float -1 ***
	.dword 	$80000000
	.byte 	$81,$80
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 131.84 ***
	.dword 	$83d70a3d
	.byte 	$88,$0
	.byte 	1     ; *** Load Float 2.468742 ***
	.dword 	$9dffde72
	.byte 	$82,$0
	.byte 	$7e   ; *** Command ~ ***
	.byte 	1     ; *** Load Float 1 ***
	.dword 	$80000000
	.byte 	$81,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 11.0 ***
	.dword 	$b0000000
	.byte 	$84,$0
	.byte 	1     ; *** Load Float 47495.970816 ***
	.dword 	$b987f887
	.byte 	$90,$0
	.byte 	$2d   ; *** Command - ***
	.byte 	1     ; *** Load Float -47484.970816 ***
	.dword 	$b97cf887
	.byte 	$90,$80
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float -671.2 ***
	.dword 	$a7cccccc
	.byte 	$8a,$80
	.byte 	1     ; *** Load Float -671.2 ***
	.dword 	$a7cccccc
	.byte 	$8a,$80
	.byte 	$2f   ; *** Command / ***
	.byte 	1     ; *** Load Float 1.0 ***
	.dword 	$80000000
	.byte 	$81,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 327.32 ***
	.dword 	$a3a8f5c2
	.byte 	$89,$0
	.byte 	1     ; *** Load Float 104.09 ***
	.dword 	$d02e147a
	.byte 	$87,$0
	.byte 	$7e   ; *** Command ~ ***
	.byte 	1     ; *** Load Float 1 ***
	.dword 	$80000000
	.byte 	$81,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float -850.64 ***
	.dword 	$d4a8f5c2
	.byte 	$8a,$80
	.byte 	1     ; *** Load Float 2.0 ***
	.dword 	$80000000
	.byte 	$82,$0
	.byte 	$2a   ; *** Command * ***
	.byte 	1     ; *** Load Float -1701.28 ***
	.dword 	$d4a8f5c2
	.byte 	$8b,$80
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 8.086521 ***
	.dword 	$816263d8
	.byte 	$84,$0
	.byte 	1     ; *** Load Float -19.0 ***
	.dword 	$98000000
	.byte 	$85,$80
	.byte 	$2a   ; *** Command * ***
	.byte 	1     ; *** Load Float -153.64389899999998 ***
	.dword 	$99a4d690
	.byte 	$88,$80
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float -550.85 ***
	.dword 	$89b66666
	.byte 	$8a,$80
	.byte 	1     ; *** Load Float -133046466091686.05 ***
	.dword 	$f20296b3
	.byte 	$af,$80
	.byte 	$7e   ; *** Command ~ ***
	.byte 	1     ; *** Load Float 1 ***
	.dword 	$80000000
	.byte 	$81,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float -474.74 ***
	.dword 	$ed5eb851
	.byte 	$89,$80
	.byte 	1     ; *** Load Float 2.557636 ***
	.dword 	$a3b04ee7
	.byte 	$82,$0
	.byte 	$2b   ; *** Command + ***
	.byte 	1     ; *** Load Float -472.182364 ***
	.dword 	$ec1757b4
	.byte 	$89,$80
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 714.69 ***
	.dword 	$b2ac28f5
	.byte 	$8a,$0
	.byte 	1     ; *** Load Float 542.51 ***
	.dword 	$87a0a3d7
	.byte 	$8a,$0
	.byte 	$2f   ; *** Command / ***
	.byte 	1     ; *** Load Float 1.3173766382186505 ***
	.dword 	$a89fcc34
	.byte 	$81,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 399.12 ***
	.dword 	$c78f5c28
	.byte 	$89,$0
	.byte 	1     ; *** Load Float 16.0 ***
	.dword 	$80000000
	.byte 	$85,$0
	.byte 	$2d   ; *** Command - ***
	.byte 	1     ; *** Load Float 383.12 ***
	.dword 	$bf8f5c28
	.byte 	$89,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 195.4 ***
	.dword 	$c3666666
	.byte 	$88,$0
	.byte 	1     ; *** Load Float 2.274403 ***
	.dword 	$918fd199
	.byte 	$82,$0
	.byte 	$7e   ; *** Command ~ ***
	.byte 	1     ; *** Load Float 1 ***
	.dword 	$80000000
	.byte 	$81,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1	; *** Load Integer 99999 ***
	.dword 	$1869f
	.byte 	0,$01
